<a href="https://colab.research.google.com/github/joshimohitm9/Deep_Learning/blob/main/Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing Library
import tensorflow as tf

# Checking the version of library
print(tf.__version__)

2.15.0


In [2]:
# creating tensors with tf.constant
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimention of tensor
scaler.ndim

0

In [4]:
# creating a vector
vector=tf.constant([2,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [5]:
# Dimention of Vector
vector.ndim

1

In [6]:
# creating a matrix
matrix=tf.constant([[2,2],[20,20]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  2],
       [20, 20]], dtype=int32)>

In [7]:
# checking the dimention of matrix
matrix.ndim

2

In [8]:
# creating another matrix
another_matrix=tf.constant([[1,1],[2,2],[3,3]],dtype=tf.float64) # using dtype for changing the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1., 1.],
       [2., 2.],
       [3., 3.]])>

In [9]:
#checking the dimnection of matrix
another_matrix.ndim

2

In [10]:
# lets create a tensor with 3 dimention
tensor=tf.constant([[[1,2,3],[1,2,3]],
                   [[2,3,4],[2,3,4]],
                    [[3,4,5],[3,4,5]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[2, 3, 4],
        [2, 3, 4]],

       [[3, 4, 5],
        [3, 4, 5]]], dtype=int32)>

In [11]:
# checking the dimention of tensor
tensor.ndim

3

* Scaler : are Single Number
* Vector : a number with direction(eg. wind and direction)
* Matrix : 2d array
* Tensor : n dimentional array of number (where n can be any number)

Creating Tensor using tf.variable

In [12]:
# using tf.varibale we can create changeable tensors whose values can be change
changeable_tensor=tf.Variable([20,7])

# using tf.constant we cant change the value of tensors
unchangeable_tensor=tf.constant([20,7])

In [13]:
changeable_tensor ,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([20,  7], dtype=int32)>)

In [14]:
# lets change the value of changeable tesor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# lets try to  change the value of unchangeable tesor
try:
  unchangeable_tensor[0].assign(7)
  unchangeable_tensor
except:
  print("not possible")


not possible


In [24]:
# crating tensor using numpy
import numpy as np
a=np.arange(1,25)
print("this is a numpy array ")
print(a)
print(87*"-")
print("this is a tensor")
tf.constant(a)

this is a numpy array 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
---------------------------------------------------------------------------------------
this is a tensor


<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>